INSERT INTO ClientTransaction (
    ClearingFirmNumber;
    DealerFirmNumber;
    AgentForFirm;
    Bin;
    FundId;
    Cusip;
    ExchangetoCusip;
    nsccControlNumber;
    nsccCorrectionIndicator;
    CurrencyIndicator;
    price;
    DistributionEventType;
    DistributionRecordDate;
    tradeDate;
    submissionDate;
    transactionRecievedDate;
    transactionRecievedTime;
    AnticipatedSettlementDate;
    nsccSettlementOverrideReasonCode;
    transactionStatus;
    workedCd;
    priceProtected;
    ContingentDeferredSalesChargeLiquidationIndicator;
    liquidationIndicator529;
    navReasonCode;
    salesChargeRate;
    DiscountCategory;
    nsccRoaLoiValue;
    ActualRoaValueSource;
    loiNumber;
    shortTermRedemptionFeeRate;
    shortTermRedemptionFeeShareAmount;
    shortTermRedemptionFeeMoneyAmount;
    ContingentDeferredSalesChargeMoneyAmount;
    moneyMarketLiquidityFeeRate;
    moneyMarketLiquidtyFeeMoneyAmount;
    taxIdNumber;
    taxIdType;
    Branch;
    representativeName;
    representativeNumber;
    stateOfSale;
    CountryCode;
    socialCode;
    moneyMarketLiquidityFeeRedemptionGateIndicator;
    moneyMarketAggregatedOrderIndicator;
    DerivedBusinessProcessingGroup;
    nsccTransactionType;
    nsccTransactionCode;
    nsccOriginalControlNumber;
    nsccOriginalCorrectionIndicator;
    nsccTestIndicator;
    nsccAsofIndicator;
    AsofReasonCode;
    nsccCustomerName;
    nsccFundAccountIndicator;
    nsccBookPhysicalShareIndicator;
    nsccRelatedTradeIndicator;
    AssetTypeIndicator;
    nsccFractionIndicator;
    GrossNetSettlementIndicator;
    nsccSecurityIssueType;
    nsccFundParticipantNumberCd;
    nsccOmnibusAccountIndicatorCd;
    nsccProgramTransactionIndicatorCd;
    nsccPeriodicFrequencyIndicatorCd;
    orderNumber;
    nsccAcatsControlNumber;
    nsccAcatsAssetsSequenceId;
    FirmRoleInTransfer;
    originatingFirmNumber;
    originatingAgentForFirm;
    originatingBIN;
    originatingFundAccount;
    originatingAccountOmnibusIndicator;
    DestinationBIN;
    DestinationFundAccount;
    DestinationAccountOmnibusIndicator;
    AsofPaymentDate;
    nsccRegistrationStatusCode;
    nsccRequestStatusCode;
)
VALUES (
    NOW(),
        'agent',
        NOW(),
        'bin',
        'anchh',
        123,
        'CountryCode',
        'CurrencyIndicator',
        123,
        'EffectOnBalance',
        'Fund_id',
        'MoneyAmount',
        'OmnibusTransaction_Id',
        123,
        'RepresentativeName',
        123,
        'SecurityId',
        'SequenceId',
        'ShareQuantity',
        'StateOfSale',
        NOW(),
        'Symbol',
        NOW(),
        'TransactionCategory',
        'TransactionSource',
        'TransactionStatus',
        'TransactionSubType',
        'TransactionType',
        'TransactionUserId');

INSERT INTO Comment (CommentText, CommentDateTime, CommentUserId)
    VALUES ('text', now(), 'IFDS');